using System;

namespace Ride
{
    /// <summary>
    /// Provides access to application log events generated by Unity so Ride systems can observe
    /// errors, warnings, assertions, standard log messages, and exceptions through a Ride-facing interface.
    /// </summary>
    public interface IApplicationLogMessageSystem : IRideSystem
    {
        /// <summary>Represents the Ride-defined categories of application log messages forwarded by this system.</summary>
        public enum LogType
        {
            Error,
            Assert,
            Warning,
            Log,
            Exception
        }

        /// <summary>
        /// Represents a callback that is invoked when the application emits a log message.
        /// </summary>
        /// <param name="condition">The main log message or exception text provided by Unity.</param>
        /// <param name="stackTrace">The stack trace associated with the log entry, if available.</param>
        /// <param name="type">The Ride log type describing the category of the message.</param>
        public delegate void LogCallback(string condition, string stackTrace, LogType type);

        /// <summary>
        /// Registers a callback to receive future application log messages observed by the system.
        /// </summary>
        /// <param name="callback">The callback to invoke when a log message is received.</param>
        void AddCallback(LogCallback callback);

        /// <summary>
        /// Unregisters a previously added callback so it no longer receives application log messages.
        /// </summary>
        /// <param name="callback">The callback to remove.</param>
        void RemoveCallback(LogCallback callback);
    }
}
