using System;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Ride.TextToSpeech
{
    /// <summary>
    /// Editor timeline view for inspecting the intermediate and final lip-sync data
    /// generated by <see cref="ElevenLabsTextToSpeech"/>.
    /// </summary>
    /// <remarks>
    /// This tool is intentionally ElevenLabs-specific for the initial implementation.
    /// It visualizes the generated audio waveform, word spans, phone spans, and final
    /// FaceFX keyframes exposed by the runtime component after a timestamped request
    /// completes.
    /// </remarks>
    public class ElevenLabsLipsyncVisualizerWindow : EditorWindow
    {
        private const float ToolbarSpacing = 6f;
        private const float RowSpacing = 6f;
        private const float WaveformHeight = 84f;
        private const float SegmentRowHeight = 28f;
        private const float CharacterRowHeight = 24f;
        private const float KeyframeRowHeight = 132f;
        private const int MaxVisibleKeyframeEntries = 8;
        private const float LabelColumnWidth = 64f;
        private const float TimelineMarginX = 12f;
        private const float MinZoomPixelsPerSecond = 40f;
        private const float MaxZoomPixelsPerSecond = 5000f;
        private const int DefaultWaveformBucketCount = 2048;

        private static readonly Color WaveformColor = new(0.23f, 0.70f, 0.95f, 1.0f);
        private static readonly Color WordColor = new(0.22f, 0.52f, 0.90f, 0.45f);
        private static readonly Color WordOutlineColor = new(0.22f, 0.52f, 0.90f, 0.90f);
        private static readonly Color FallbackWordColor = new(0.86f, 0.60f, 0.22f, 0.38f);
        private static readonly Color FallbackWordOutlineColor = new(0.90f, 0.68f, 0.28f, 0.82f);
        private static readonly Color CharacterColor = new(0.62f, 0.40f, 0.95f, 0.40f);
        private static readonly Color CharacterOutlineColor = new(0.62f, 0.40f, 0.95f, 0.90f);
        private static readonly Color PhoneColor = new(0.18f, 0.72f, 0.45f, 0.45f);
        private static readonly Color PhoneOutlineColor = new(0.18f, 0.72f, 0.45f, 0.90f);
        private static readonly Color KeyframeColor = new(0.98f, 0.71f, 0.18f, 0.95f);
        private static readonly Color PlayheadColor = new(1.0f, 0.28f, 0.28f, 1.0f);
        private static readonly Color HoverColor = new(1.0f, 1.0f, 1.0f, 0.35f);
        private static readonly Color PinnedColor = new(1.0f, 0.95f, 0.25f, 0.85f);
        private static readonly Color TimelineBackgroundColor = new(0.14f, 0.14f, 0.14f, 1.0f);
        private static readonly Color RowBackgroundColor = new(0.18f, 0.18f, 0.18f, 1.0f);
        private static readonly Color GridColor = new(1f, 1f, 1f, 0.08f);

        private ElevenLabsTextToSpeech m_target;
        private bool m_followSelection = true;
        private float m_zoomPixelsPerSecond = 140f;
        private float m_startTimeSeconds;
        private double m_hoverTimeSeconds = -1.0;
        private double m_pinnedTimeSeconds = -1.0;
        private bool m_draggingPinnedInspection;

        private AudioClip m_cachedClip;
        private float[] m_cachedWaveformPeaks = Array.Empty<float>();
        private int m_cachedWaveformBucketCount;


        [MenuItem("Ride/Cognition/TTS/ElevenLabs Lipsync Visualizer")]
        public static void Open()
        {
            var window = GetWindow<ElevenLabsLipsyncVisualizerWindow>("ElevenLabs Lipsync");
            window.minSize = new Vector2(900f, 520f);
            window.Show();
        }

        private void OnEnable()
        {
            EditorApplication.update += OnEditorUpdate;
            Selection.selectionChanged += OnSelectionChanged;
            OnSelectionChanged();
        }

        private void OnDisable()
        {
            EditorApplication.update -= OnEditorUpdate;
            Selection.selectionChanged -= OnSelectionChanged;
        }

        private void OnSelectionChanged()
        {
            if (!m_followSelection)
                return;

            var selected = Selection.activeGameObject;
            if (selected == null)
            {
                SetTarget(null);
                return;
            }

            SetTarget(selected.GetComponent<ElevenLabsTextToSpeech>());
        }

        private void OnEditorUpdate()
        {
            if (m_followSelection)
                OnSelectionChanged();

            if (m_target == null)
                return;

            if (GetCurrentClip() != null)
                Repaint();
        }

        private void SetTarget(ElevenLabsTextToSpeech target)
        {
            if (ReferenceEquals(m_target, target))
                return;

            m_target = target;
            m_hoverTimeSeconds = -1.0;
            m_pinnedTimeSeconds = -1.0;
            InvalidateWaveformCache();
            Repaint();
        }

        private void InvalidateWaveformCache()
        {
            m_cachedClip = null;
            m_cachedWaveformPeaks = Array.Empty<float>();
            m_cachedWaveformBucketCount = 0;
        }

        private void OnGUI()
        {
            DrawToolbar();
            EditorGUILayout.Space(ToolbarSpacing);

            if (m_target == null)
            {
                EditorGUILayout.HelpBox(
                    "Select a GameObject with an ElevenLabsTextToSpeech component, or assign one directly. " +
                    "After GetAudioClipWithTimestamps() runs, this window will visualize the generated schedule.",
                    MessageType.Info);
                return;
            }

            AudioClip clip = GetCurrentClip();
            RebuildWaveformCacheIfNeeded(clip);

            double scheduleDuration = GetScheduleDurationSeconds();
            double audioDuration = clip != null ? clip.length : 0.0;
            double durationSeconds = Math.Max(scheduleDuration, audioDuration);

            DrawSummaryPanel(clip, durationSeconds);

            if (durationSeconds <= 0.0)
            {
                EditorGUILayout.HelpBox(
                    "No generated clip or schedule data is currently available on the selected ElevenLabsTextToSpeech component.",
                    MessageType.Warning);
                return;
            }

            Rect controlsRect = GUILayoutUtility.GetRect(10f, 54f, GUILayout.ExpandWidth(true));
            DrawTimelineControls(controlsRect, (float)durationSeconds);

            Rect timelineRect = GUILayoutUtility.GetRect(10f, GetTimelineHeight(), GUILayout.ExpandWidth(true));
            DrawTimeline(timelineRect, clip, durationSeconds);
        }

        private void DrawToolbar()
        {
            using (new EditorGUILayout.HorizontalScope(EditorStyles.toolbar))
            {
                var nextTarget = (ElevenLabsTextToSpeech)EditorGUILayout.ObjectField(
                    m_target,
                    typeof(ElevenLabsTextToSpeech),
                    true,
                    GUILayout.MinWidth(260f));

                if (!ReferenceEquals(nextTarget, m_target))
                    SetTarget(nextTarget);

                GUILayout.Space(8f);

                bool followSelection = GUILayout.Toggle(m_followSelection, "Follow Selection", EditorStyles.toolbarButton, GUILayout.Width(110f));
                if (followSelection != m_followSelection)
                {
                    m_followSelection = followSelection;
                    if (m_followSelection)
                        OnSelectionChanged();
                }

                GUI.enabled = m_target != null;

                if (GUILayout.Button("Frame All", EditorStyles.toolbarButton, GUILayout.Width(80f)))
                    FrameEntireTimeline();

                if (GUILayout.Button("Now", EditorStyles.toolbarButton, GUILayout.Width(60f)))
                    FrameCurrentPlaybackTime();

                if (Application.isPlaying && m_target != null && m_target.audioSource != null && m_target.audioSource.clip != null)
                {
                    if (!m_target.audioSource.isPlaying)
                    {
                        if (GUILayout.Button("Play", EditorStyles.toolbarButton, GUILayout.Width(60f)))
                            m_target.audioSource.Play();
                    }
                    else
                    {
                        if (GUILayout.Button("Stop", EditorStyles.toolbarButton, GUILayout.Width(60f)))
                            m_target.audioSource.Stop();
                    }
                }

                if (GUILayout.Button("Clear Pin", EditorStyles.toolbarButton, GUILayout.Width(70f)))
                    m_pinnedTimeSeconds = -1.0;

                if (GUILayout.Button("Refresh", EditorStyles.toolbarButton, GUILayout.Width(70f)))
                {
                    InvalidateWaveformCache();
                    Repaint();
                }

                GUI.enabled = true;
                GUILayout.FlexibleSpace();
            }
        }

        private void DrawSummaryPanel(AudioClip clip, double durationSeconds)
        {
            using (new EditorGUILayout.VerticalScope(EditorStyles.helpBox))
            {
                EditorGUILayout.LabelField("Snapshot", EditorStyles.boldLabel);

                string clipName = clip != null ? clip.name : "<none>";
                string audioState = GetAudioStateLabel();

                EditorGUILayout.LabelField($"Target: {(m_target != null ? m_target.name : "<none>")}");
                EditorGUILayout.LabelField($"Clip: {clipName}");
                EditorGUILayout.LabelField($"Audio: {audioState}");
                EditorGUILayout.LabelField($"Duration: {durationSeconds:0.000}s");
                EditorGUILayout.LabelField($"Words: {m_target.LastWordSegments.Count}   Phones: {m_target.LastPhoneSegments.Count}   Keyframes: {m_target.LastFacefxKeyframes.Count}");

                double inspectedTime = GetInspectedTimeSeconds();
                if (inspectedTime >= 0.0)
                    EditorGUILayout.LabelField(BuildInspectionSummary(inspectedTime));
            }
        }

        private void DrawTimelineControls(Rect rect, float durationSeconds)
        {
            Rect row1 = new(rect.x, rect.y, rect.width, 18f);
            Rect row2 = new(rect.x, rect.y + 24f, rect.width, 18f);

            float viewportWidth = GetTimelineViewportWidth(rect.width);
            float zoomBefore = m_zoomPixelsPerSecond;
            float visibleDuration = GetVisibleDurationSeconds(viewportWidth);
            float anchorTime = GetZoomAnchorTime(durationSeconds, visibleDuration);

            EditorGUI.LabelField(new Rect(row1.x, row1.y, 55f, row1.height), "Zoom");
            m_zoomPixelsPerSecond = GUI.HorizontalSlider(
                new Rect(row1.x + 52f, row1.y + 2f, Mathf.Max(120f, row1.width - 130f), 16f),
                m_zoomPixelsPerSecond,
                MinZoomPixelsPerSecond,
                MaxZoomPixelsPerSecond);
            EditorGUI.LabelField(new Rect(row1.xMax - 70f, row1.y, 70f, row1.height), $"{m_zoomPixelsPerSecond:0} px/s");

            if (!Mathf.Approximately(zoomBefore, m_zoomPixelsPerSecond))
                ReframeAroundAnchor(anchorTime, durationSeconds, viewportWidth);

            visibleDuration = GetVisibleDurationSeconds(viewportWidth);
            float maxStart = Mathf.Max(0f, durationSeconds - visibleDuration);
            m_startTimeSeconds = Mathf.Clamp(m_startTimeSeconds, 0f, maxStart);
            EditorGUI.LabelField(new Rect(row2.x, row2.y, 55f, row2.height), "Start");
            m_startTimeSeconds = GUI.HorizontalSlider(
                new Rect(row2.x + 52f, row2.y + 2f, Mathf.Max(120f, row2.width - 200f), 16f),
                m_startTimeSeconds,
                0f,
                maxStart <= 0f ? 0.0001f : maxStart);

            Rect visibleLabelRect = new(row2.xMax - 140f, row2.y, 140f, row2.height);
            EditorGUI.LabelField(visibleLabelRect, $"View {visibleDuration:0.00}s");
        }

        private void DrawTimeline(Rect rect, AudioClip clip, double durationSeconds)
        {
            EditorGUI.DrawRect(rect, TimelineBackgroundColor);

            Rect labelColumnRect = new(
                rect.x + TimelineMarginX,
                rect.y + TimelineMarginX,
                LabelColumnWidth,
                rect.height - (TimelineMarginX * 2f));

            Rect contentRect = new(
                labelColumnRect.xMax + 6f,
                rect.y + TimelineMarginX,
                rect.width - (TimelineMarginX * 2f) - LabelColumnWidth - 6f,
                rect.height - (TimelineMarginX * 2f));

            if (contentRect.width <= 0f || contentRect.height <= 0f)
                return;

            float visibleDuration = GetVisibleDurationSeconds(contentRect.width);
            double endTimeSeconds = m_startTimeSeconds + visibleDuration;

            Rect waveformRect = new(contentRect.x, contentRect.y, contentRect.width, WaveformHeight);
            Rect wordRect = new(contentRect.x, waveformRect.yMax + RowSpacing, contentRect.width, SegmentRowHeight);
            Rect characterRect = new(contentRect.x, wordRect.yMax + RowSpacing, contentRect.width, CharacterRowHeight);
            Rect phoneRect = new(contentRect.x, characterRect.yMax + RowSpacing, contentRect.width, SegmentRowHeight);
            Rect keyframeRect = new(contentRect.x, phoneRect.yMax + RowSpacing, contentRect.width, KeyframeRowHeight);
            Rect labelsRect = new(labelColumnRect.x, contentRect.y, labelColumnRect.width, keyframeRect.yMax - contentRect.y);

            DrawRowBackground(waveformRect);
            DrawRowBackground(wordRect);
            DrawRowBackground(characterRect);
            DrawRowBackground(phoneRect);
            DrawRowBackground(keyframeRect);

            DrawRowLabel(labelsRect, waveformRect, "Audio");
            DrawRowLabel(labelsRect, wordRect, "Words");
            DrawRowLabel(labelsRect, characterRect, "Chars");
            DrawRowLabel(labelsRect, phoneRect, "Phones");
            DrawRowLabel(labelsRect, keyframeRect, "FaceFX");

            DrawTimeGrid(waveformRect, m_startTimeSeconds, endTimeSeconds);
            DrawWaveform(waveformRect, clip, durationSeconds, m_startTimeSeconds, endTimeSeconds);
            DrawWordSegments(wordRect, m_startTimeSeconds, endTimeSeconds);
            DrawCharacterSegments(characterRect, m_startTimeSeconds, endTimeSeconds);
            DrawPhoneSegments(phoneRect, m_startTimeSeconds, endTimeSeconds);
            DrawKeyframes(keyframeRect, m_startTimeSeconds, endTimeSeconds);

            HandleTimelineMouse(contentRect, m_startTimeSeconds, endTimeSeconds);
            DrawOverlayLines(contentRect, m_startTimeSeconds, endTimeSeconds);
        }

        private static float GetTimelineHeight() => WaveformHeight + SegmentRowHeight + CharacterRowHeight + SegmentRowHeight + KeyframeRowHeight + (TimelineMarginX * 2f) + (RowSpacing * 4f);

        private void DrawRowBackground(Rect rect)
        {
            EditorGUI.DrawRect(rect, RowBackgroundColor);
            Handles.BeginGUI();
            Handles.color = new Color(1f, 1f, 1f, 0.06f);
            Handles.DrawAAPolyLine(1f, new Vector3(rect.xMin, rect.yMax), new Vector3(rect.xMax, rect.yMax));
            Handles.EndGUI();
        }

        private static void DrawRowLabel(Rect labelColumnRect, Rect rowRect, string label)
        {
            Rect labelRect = new(labelColumnRect.x, rowRect.y, Mathf.Max(0f, labelColumnRect.width), rowRect.height);
            GUI.Label(labelRect, label, EditorStyles.miniBoldLabel);
        }

        private void DrawTimeGrid(Rect rect, double startTimeSeconds, double endTimeSeconds)
        {
            double visibleDuration = Math.Max(0.001, endTimeSeconds - startTimeSeconds);
            double step = GetGridStepSeconds(visibleDuration);

            Handles.BeginGUI();
            Handles.color = GridColor;

            double first = Math.Floor(startTimeSeconds / step) * step;
            for (double t = first; t <= endTimeSeconds + step; t += step)
            {
                float x = TimeToPixel(rect, t, startTimeSeconds, endTimeSeconds);
                Handles.DrawLine(new Vector3(x, rect.yMin), new Vector3(x, rect.yMax));

                Rect labelRect = new(x + 2f, rect.yMin + 2f, 48f, 14f);
                GUI.Label(labelRect, $"{t:0.00}", EditorStyles.miniLabel);
            }

            Handles.EndGUI();
        }

        private void DrawWaveform(Rect rect, AudioClip clip, double durationSeconds, double startTimeSeconds, double endTimeSeconds)
        {
            if (clip == null || m_cachedWaveformPeaks == null || m_cachedWaveformPeaks.Length == 0 || durationSeconds <= 0.0)
                return;

            Handles.BeginGUI();
            Handles.color = WaveformColor;

            float centerY = rect.center.y;
            float halfHeight = rect.height * 0.42f;
            int maxIndex = m_cachedWaveformPeaks.Length - 1;

            for (int x = 0; x < Mathf.CeilToInt(rect.width); x++)
            {
                double time = PixelToTime(rect, rect.x + x, startTimeSeconds, endTimeSeconds);
                if (time < 0.0 || time > durationSeconds)
                    continue;

                int index = Mathf.Clamp((int)Math.Round((time / durationSeconds) * maxIndex), 0, maxIndex);
                float peak = Mathf.Clamp01(m_cachedWaveformPeaks[index]);
                float amplitude = peak * halfHeight;
                Handles.DrawLine(
                    new Vector3(rect.x + x, centerY - amplitude),
                    new Vector3(rect.x + x, centerY + amplitude));
            }

            Handles.EndGUI();
        }

        private void DrawWordSegments(Rect rect, double startTimeSeconds, double endTimeSeconds)
        {
            for (int i = 0; i < m_target.LastWordSegments.Count; i++)
            {
                var segment = m_target.LastWordSegments[i];
                if (segment.EndTimeSeconds < startTimeSeconds || segment.StartTimeSeconds > endTimeSeconds)
                    continue;

                Rect segmentRect = SegmentToRect(rect, segment.StartTimeSeconds, segment.EndTimeSeconds, startTimeSeconds, endTimeSeconds);
                GetWordSegmentColors(i, out Color fillColor, out Color outlineColor);
                DrawSegmentBox(segmentRect, fillColor, outlineColor, segment.Word);
            }
        }

        private void DrawCharacterSegments(Rect rect, double startTimeSeconds, double endTimeSeconds)
        {
            ElevenLabsTextToSpeech.ElevenLabsAlignment alignment = GetCurrentAlignment();
            if (alignment == null ||
                alignment.characters == null ||
                alignment.character_start_times_seconds == null ||
                alignment.character_end_times_seconds == null)
                return;

            char[] chars = alignment.ToCharArray();
            double[] starts = alignment.character_start_times_seconds;
            double[] ends = alignment.character_end_times_seconds;
            int count = Math.Min(chars.Length, Math.Min(starts.Length, ends.Length));

            for (int i = 0; i < count; i++)
            {
                double start = starts[i];
                double end = ends[i];
                if (end < start)
                    end = start;

                if (end < startTimeSeconds || start > endTimeSeconds)
                    continue;

                string label = chars[i] switch
                {
                    ' ' => "<sp>",
                    '\0' => "<nul>",
                    _ => chars[i].ToString()
                };

                Rect segmentRect = SegmentToRect(rect, start, end, startTimeSeconds, endTimeSeconds);
                DrawSegmentBox(segmentRect, CharacterColor, CharacterOutlineColor, label);
            }
        }

        private void DrawPhoneSegments(Rect rect, double startTimeSeconds, double endTimeSeconds)
        {
            for (int i = 0; i < m_target.LastPhoneSegments.Count; i++)
            {
                var segment = m_target.LastPhoneSegments[i];
                if (segment.EndTimeSeconds < startTimeSeconds || segment.StartTimeSeconds > endTimeSeconds)
                    continue;

                Rect segmentRect = SegmentToRect(rect, segment.StartTimeSeconds, segment.EndTimeSeconds, startTimeSeconds, endTimeSeconds);
                string label = BuildPhoneLabel(segment.IpaToken);
                DrawSegmentBox(segmentRect, PhoneColor, PhoneOutlineColor, label);
            }
        }

        private void DrawKeyframes(Rect rect, double startTimeSeconds, double endTimeSeconds)
        {
            Handles.BeginGUI();
            Handles.color = KeyframeColor;

            for (int i = 0; i < m_target.LastFacefxKeyframes.Count; i++)
            {
                var keyframe = m_target.LastFacefxKeyframes[i];
                if (keyframe.TimeSeconds < startTimeSeconds || keyframe.TimeSeconds > endTimeSeconds)
                    continue;

                float x = TimeToPixel(rect, keyframe.TimeSeconds, startTimeSeconds, endTimeSeconds);
                Handles.DrawLine(new Vector3(x, rect.yMin + 2f), new Vector3(x, rect.yMax - 2f));

                string[] labels = BuildKeyframeLabels(keyframe, maxVisibleEntries: MaxVisibleKeyframeEntries);
                for (int labelIndex = 0; labelIndex < labels.Length; labelIndex++)
                {
                    Rect labelRect = new(x + 2f, rect.yMin + 2f + (labelIndex * 14f), 120f, 14f);
                    GUI.Label(labelRect, labels[labelIndex], EditorStyles.miniLabel);
                }
            }

            Handles.EndGUI();
        }

        private static void DrawSegmentBox(Rect rect, Color fill, Color outline, string label)
        {
            if (rect.width <= 0f)
                return;

            EditorGUI.DrawRect(rect, fill);
            Handles.BeginGUI();
            Handles.color = outline;
            Handles.DrawAAPolyLine(
                1.0f,
                new Vector3(rect.xMin, rect.yMin),
                new Vector3(rect.xMax, rect.yMin),
                new Vector3(rect.xMax, rect.yMax),
                new Vector3(rect.xMin, rect.yMax),
                new Vector3(rect.xMin, rect.yMin));
            Handles.EndGUI();

            if (rect.width >= 26f)
                GUI.Label(new Rect(rect.x + 3f, rect.y + 2f, rect.width - 6f, rect.height - 4f), label, EditorStyles.miniLabel);
        }

        private void HandleTimelineMouse(Rect rect, double startTimeSeconds, double endTimeSeconds)
        {
            Event evt = Event.current;
            int controlId = GUIUtility.GetControlID(FocusType.Passive);

            if (evt.rawType == EventType.MouseUp && GUIUtility.hotControl == controlId)
            {
                GUIUtility.hotControl = 0;
                m_draggingPinnedInspection = false;
            }

            if (!rect.Contains(evt.mousePosition) && !(m_draggingPinnedInspection && GUIUtility.hotControl == controlId))
            {
                if (evt.type == EventType.MouseMove && m_hoverTimeSeconds >= 0.0)
                {
                    m_hoverTimeSeconds = -1.0;
                    Repaint();
                }

                return;
            }

            double time = PixelToTime(rect, evt.mousePosition.x, startTimeSeconds, endTimeSeconds);

            if (evt.type == EventType.MouseMove)
            {
                m_hoverTimeSeconds = time;
                Repaint();
            }
            else if (evt.type == EventType.MouseDown && evt.button == 0)
            {
                m_pinnedTimeSeconds = time;
                m_draggingPinnedInspection = true;
                GUIUtility.hotControl = controlId;
                Repaint();
                evt.Use();
            }
            else if (evt.type == EventType.MouseDrag && evt.button == 0 && GUIUtility.hotControl == controlId)
            {
                m_pinnedTimeSeconds = time;
                Repaint();
                evt.Use();
            }
        }

        private void DrawOverlayLines(Rect rect, double startTimeSeconds, double endTimeSeconds)
        {
            Handles.BeginGUI();

            double playhead = GetPlaybackTimeSeconds();
            if (playhead >= startTimeSeconds && playhead <= endTimeSeconds)
            {
                Handles.color = PlayheadColor;
                float x = TimeToPixel(rect, playhead, startTimeSeconds, endTimeSeconds);
                Handles.DrawAAPolyLine(2f, new Vector3(x, rect.yMin), new Vector3(x, rect.yMax));
            }

            if (m_hoverTimeSeconds >= startTimeSeconds && m_hoverTimeSeconds <= endTimeSeconds)
            {
                Handles.color = HoverColor;
                float x = TimeToPixel(rect, m_hoverTimeSeconds, startTimeSeconds, endTimeSeconds);
                Handles.DrawAAPolyLine(1.5f, new Vector3(x, rect.yMin), new Vector3(x, rect.yMax));
            }

            if (m_pinnedTimeSeconds >= startTimeSeconds && m_pinnedTimeSeconds <= endTimeSeconds)
            {
                Handles.color = PinnedColor;
                float x = TimeToPixel(rect, m_pinnedTimeSeconds, startTimeSeconds, endTimeSeconds);
                Handles.DrawAAPolyLine(2f, new Vector3(x, rect.yMin), new Vector3(x, rect.yMax));
            }

            Handles.EndGUI();
        }

        private void FrameEntireTimeline()
        {
            m_startTimeSeconds = 0f;
            m_zoomPixelsPerSecond = MinZoomPixelsPerSecond;
            Repaint();
        }

        private void FrameCurrentPlaybackTime()
        {
            if (m_target == null || m_target.audioSource == null)
                return;

            float currentTime = m_target.audioSource.time;
            float visibleDuration = GetVisibleDurationSeconds(GetTimelineViewportWidth(position.width));
            m_startTimeSeconds = Mathf.Max(0f, currentTime - (visibleDuration * 0.25f));
            Repaint();
        }

        private AudioClip GetCurrentClip()
        {
            if (m_target == null)
                return null;

            if (m_target.audioSource != null && m_target.audioSource.clip != null)
                return m_target.audioSource.clip;

            return m_target.LastGeneratedAudioClip;
        }

        private ElevenLabsTextToSpeech.ElevenLabsAlignment GetCurrentAlignment()
        {
            if (m_target == null || m_target.LastTimestampsResult == null)
                return null;

            return m_target.LastTimestampsResult.normalized_alignment ?? m_target.LastTimestampsResult.alignment;
        }

        private string GetAudioStateLabel()
        {
            if (m_target == null || m_target.audioSource == null)
                return "No AudioSource";

            if (m_target.audioSource.clip == null)
                return "No clip";

            return m_target.audioSource.isPlaying
                ? $"Playing @ {m_target.audioSource.time:0.000}s"
                : "Ready";
        }

        private double GetPlaybackTimeSeconds()
        {
            if (m_target == null || m_target.audioSource == null || !m_target.audioSource.isPlaying)
                return -1.0;

            return m_target.audioSource.time;
        }

        private double GetInspectedTimeSeconds()
        {
            if (m_pinnedTimeSeconds >= 0.0)
                return m_pinnedTimeSeconds;

            if (m_hoverTimeSeconds >= 0.0)
                return m_hoverTimeSeconds;

            double playback = GetPlaybackTimeSeconds();
            return playback >= 0.0 ? playback : -1.0;
        }

        private string BuildInspectionSummary(double timeSeconds)
        {
            StringBuilder sb = new();
            sb.Append($"Inspect @ {timeSeconds:0.000}s");

            var word = FindWordAtTime(timeSeconds);
            if (word.HasValue)
            {
                string sourceLabel = IsFallbackWord(word.Value)
                    ? "fallback"
                    : "IPA";
                sb.Append($" | Word: {word.Value.Word} [{word.Value.StartTimeSeconds:0.000}-{word.Value.EndTimeSeconds:0.000}] ({sourceLabel})");
            }

            var phone = FindPhoneAtTime(timeSeconds);
            if (phone.HasValue)
                sb.Append($" | Phone: {BuildPhoneLabel(phone.Value.IpaToken)}");

            var keyframe = FindNearestKeyframe(timeSeconds, 0.060);
            if (keyframe.HasValue)
                sb.Append($" | Keyframe: {string.Join(", ", BuildKeyframeLabels(keyframe.Value, maxVisibleEntries: MaxVisibleKeyframeEntries))}");

            return sb.ToString();
        }

        private ElevenLabsTextToSpeech.WordSegment? FindWordAtTime(double timeSeconds)
        {
            for (int i = 0; i < m_target.LastWordSegments.Count; i++)
            {
                var word = m_target.LastWordSegments[i];
                if (timeSeconds >= word.StartTimeSeconds && timeSeconds <= word.EndTimeSeconds)
                    return word;
            }

            return null;
        }

        private bool IsFallbackWord(ElevenLabsTextToSpeech.WordSegment word)
        {
            for (int i = 0; i < m_target.LastWordIpaSegments.Count; i++)
            {
                var segment = m_target.LastWordIpaSegments[i];
                if (segment.Word.StartTimeSeconds == word.StartTimeSeconds &&
                    segment.Word.EndTimeSeconds == word.EndTimeSeconds &&
                    string.Equals(segment.Word.Word, word.Word, StringComparison.Ordinal))
                    return !segment.HasIpa;
            }

            return false;
        }

        private void GetWordSegmentColors(int wordIndex, out Color fillColor, out Color outlineColor)
        {
            bool hasIpa = wordIndex >= 0 &&
                wordIndex < m_target.LastWordIpaSegments.Count &&
                m_target.LastWordIpaSegments[wordIndex].HasIpa;

            fillColor = hasIpa ? WordColor : FallbackWordColor;
            outlineColor = hasIpa ? WordOutlineColor : FallbackWordOutlineColor;
        }

        private ElevenLabsTextToSpeech.PhoneSegment? FindPhoneAtTime(double timeSeconds)
        {
            for (int i = 0; i < m_target.LastPhoneSegments.Count; i++)
            {
                var phone = m_target.LastPhoneSegments[i];
                if (timeSeconds >= phone.StartTimeSeconds && timeSeconds <= phone.EndTimeSeconds)
                    return phone;
            }

            return null;
        }

        private ElevenLabsTextToSpeech.FacefxKeyframe? FindNearestKeyframe(double timeSeconds, double toleranceSeconds)
        {
            double bestDistance = toleranceSeconds;
            ElevenLabsTextToSpeech.FacefxKeyframe? best = null;

            for (int i = 0; i < m_target.LastFacefxKeyframes.Count; i++)
            {
                var keyframe = m_target.LastFacefxKeyframes[i];
                double distance = Math.Abs(keyframe.TimeSeconds - timeSeconds);
                if (distance <= bestDistance)
                {
                    bestDistance = distance;
                    best = keyframe;
                }
            }

            return best;
        }

        private static string BuildPhoneLabel(string ipaToken)
        {
            if (string.IsNullOrEmpty(ipaToken))
                return "<none>";

            if (ElevenLabsTextToSpeech.TryGetFacefxPhonemeLabel(ipaToken, out string label))
                return $"{ipaToken}->{label}";

            return $"{ipaToken}->?";
        }

        private static string[] BuildKeyframeLabels(ElevenLabsTextToSpeech.FacefxKeyframe keyframe, int maxVisibleEntries)
        {
            if (keyframe.FacefxVisemes == null || keyframe.FacefxVisemes.Length == 0)
                return new[] { "<empty>" };

            if (keyframe.Amounts == null || keyframe.Amounts.Length == 0)
                return new[] { keyframe.FacefxVisemes[0] };

            int count = Math.Min(keyframe.FacefxVisemes.Length, keyframe.Amounts.Length);
            if (count == 0)
                return new[] { "<empty>" };

            string[] lines = new string[Mathf.Max(1, maxVisibleEntries)];
            int visibleCount = 0;
            int hiddenCount = 0;

            for (int i = 0; i < count; i++)
            {
                float amount = keyframe.Amounts[i];
                if (Mathf.Approximately(amount, 0f))
                    continue;

                if (visibleCount < maxVisibleEntries)
                {
                    lines[visibleCount] = $"{keyframe.FacefxVisemes[i]}={amount:0.00}";
                    visibleCount++;
                }
                else
                {
                    hiddenCount++;
                }
            }

            if (visibleCount == 0)
                return new[] { "<zero>" };

            if (hiddenCount > 0)
            {
                if (visibleCount == maxVisibleEntries)
                    lines[visibleCount - 1] = $"+{hiddenCount + 1} more";
                else
                    lines[visibleCount++] = $"+{hiddenCount} more";
            }

            string[] result = new string[visibleCount];
            Array.Copy(lines, result, visibleCount);
            return result;
        }

        private void RebuildWaveformCacheIfNeeded(AudioClip clip)
        {
            if (clip == null)
            {
                InvalidateWaveformCache();
                return;
            }

            if (ReferenceEquals(m_cachedClip, clip) &&
                m_cachedWaveformPeaks != null &&
                m_cachedWaveformPeaks.Length > 0 &&
                m_cachedWaveformBucketCount == DefaultWaveformBucketCount)
                return;

            m_cachedClip = clip;
            m_cachedWaveformBucketCount = DefaultWaveformBucketCount;
            m_cachedWaveformPeaks = BuildWaveformPeakCache(clip, DefaultWaveformBucketCount);
        }

        private static float[] BuildWaveformPeakCache(AudioClip clip, int bucketCount)
        {
            if (clip == null || bucketCount <= 0 || clip.samples <= 0 || clip.channels <= 0)
                return Array.Empty<float>();

            float[] data = new float[clip.samples * clip.channels];
            try
            {
                clip.GetData(data, 0);
            }
            catch
            {
                return Array.Empty<float>();
            }

            float[] peaks = new float[bucketCount];
            int totalFrames = clip.samples;
            int framesPerBucket = Mathf.Max(1, Mathf.CeilToInt(totalFrames / (float)bucketCount));

            for (int bucket = 0; bucket < bucketCount; bucket++)
            {
                int startFrame = bucket * framesPerBucket;
                int endFrame = Mathf.Min(totalFrames, startFrame + framesPerBucket);
                float peak = 0f;

                for (int frame = startFrame; frame < endFrame; frame++)
                {
                    int sampleIndex = frame * clip.channels;
                    float mixed = 0f;

                    for (int channel = 0; channel < clip.channels; channel++)
                        mixed += Mathf.Abs(data[sampleIndex + channel]);

                    peak = Mathf.Max(peak, mixed / clip.channels);
                }

                peaks[bucket] = peak;
            }

            return peaks;
        }

        private double GetScheduleDurationSeconds()
        {
            double duration = 0.0;

            if (m_target == null)
                return duration;

            for (int i = 0; i < m_target.LastWordSegments.Count; i++)
                duration = Math.Max(duration, m_target.LastWordSegments[i].EndTimeSeconds);

            for (int i = 0; i < m_target.LastPhoneSegments.Count; i++)
                duration = Math.Max(duration, m_target.LastPhoneSegments[i].EndTimeSeconds);

            for (int i = 0; i < m_target.LastFacefxKeyframes.Count; i++)
                duration = Math.Max(duration, m_target.LastFacefxKeyframes[i].TimeSeconds);

            return duration;
        }

        private float GetTimelineViewportWidth(float totalWidth) => Mathf.Max(10f, totalWidth - (TimelineMarginX * 2f) - LabelColumnWidth - 6f);

        private float GetZoomAnchorTime(float durationSeconds, float visibleDuration)
        {
            double inspectedTime = GetInspectedTimeSeconds();
            if (inspectedTime >= 0.0)
                return Mathf.Clamp((float)inspectedTime, 0f, durationSeconds);

            return Mathf.Clamp(m_startTimeSeconds + (visibleDuration * 0.5f), 0f, durationSeconds);
        }

        private void ReframeAroundAnchor(float anchorTime, float durationSeconds, float viewportWidth)
        {
            float newVisibleDuration = GetVisibleDurationSeconds(viewportWidth);
            float maxStart = Mathf.Max(0f, durationSeconds - newVisibleDuration);
            m_startTimeSeconds = Mathf.Clamp(anchorTime - (newVisibleDuration * 0.5f), 0f, maxStart);
        }

        private float GetVisibleDurationSeconds(float viewportWidth) => Mathf.Max(0.1f, viewportWidth / Mathf.Max(MinZoomPixelsPerSecond, m_zoomPixelsPerSecond));

        private static double GetGridStepSeconds(double visibleDurationSeconds)
        {
            if (visibleDurationSeconds <= 1.5) return 0.1;
            if (visibleDurationSeconds <= 3.0) return 0.25;
            if (visibleDurationSeconds <= 7.0) return 0.5;
            if (visibleDurationSeconds <= 14.0) return 1.0;
            return 2.0;
        }

        private static Rect SegmentToRect(Rect rowRect, double startTime, double endTime, double visibleStartTime, double visibleEndTime)
        {
            double clampedStart = Math.Max(startTime, visibleStartTime);
            double clampedEnd = Math.Min(endTime, visibleEndTime);
            float xMin = TimeToPixel(rowRect, clampedStart, visibleStartTime, visibleEndTime);
            float xMax = TimeToPixel(rowRect, clampedEnd, visibleStartTime, visibleEndTime);
            return new Rect(xMin, rowRect.y + 2f, Mathf.Max(1f, xMax - xMin), rowRect.height - 4f);
        }

        private static float TimeToPixel(Rect rect, double timeSeconds, double visibleStartTime, double visibleEndTime)
        {
            double span = Math.Max(0.0001, visibleEndTime - visibleStartTime);
            double t = (timeSeconds - visibleStartTime) / span;
            return rect.x + (float)(t * rect.width);
        }

        private static double PixelToTime(Rect rect, float pixelX, double visibleStartTime, double visibleEndTime)
        {
            double span = Math.Max(0.0001, visibleEndTime - visibleStartTime);
            double t = Mathf.InverseLerp(rect.xMin, rect.xMax, pixelX);
            return visibleStartTime + (span * t);
        }
    }
}
